name: Alpha
description: Alphs template for Jekyll
baseurl: '/Alpha-Jekyll-Theme'

url: "http://localhost:4000"

paginate: 10


[jekyll-new](https://github.com/jglovier/jekyll-new)


[jekyll](https://github.com/jekyll/jekyll)